### ISSUE TITLE
json parse exception

### ISSUE THREAD

**Issue by gamerson** [angelozerr/tern.java#186]
With the aui plugin enabled and in .js file if I do code assist like :

AUI().use('aui-base', function(A) {
        new A.<content assist>
});

it will get no proposals and in the tern console I get the following error:

```
-----------------------------------
Tern request#:
{"files":[{"name":"docroot/js/main.js","text":"AUI().use('aui-base', function(A) {\r\n\tnew A.\r\n});\r\n\r\naui","type":"full"}]}

Tern response# with 19ms:
-----------------------------------
{}
-----------------------------------
Tern request#completions:
{"query":{"type":"completions","file":"docroot/js/main.js","end":44,"types":true,"docs":true,"urls":true,"origins":true,"caseInsensitive":true,"lineCharPositions":false,"expandWordForward":false,"omitObjectPrototype":false,"file":"docroot/js/main.js"}}

Tern error#completions with 26ms:
java.io.IOException: com.eclipsesource.json.ParseException: Expected ',' or '}' at 1:164673
        at tern.server.nodejs.NodejsTernHelper.makeRequest(NodejsTernHelper.java:106)
        at tern.server.nodejs.NodejsTernServer.makeRequest(NodejsTernServer.java:172)
        at tern.server.nodejs.NodejsTernServer.request(NodejsTernServer.java:237)
        at tern.resources.TernProject.request(TernProject.java:460)
        at tern.resources.TernProject.request(TernProject.java:449)
        at tern.eclipse.ide.jsdt.internal.contentassist.TernCompletionProposalComputer.computeCompletionProposals(TernCompletionProposalComputer.java:75)
        at org.eclipse.wst.jsdt.internal.ui.text.java.CompletionProposalComputerDescriptor.computeCompletionProposals(CompletionProposalComputerDescriptor.java:298)
        at org.eclipse.wst.jsdt.internal.ui.text.java.CompletionProposalCategory.computeCompletionProposals(CompletionProposalCategory.java:258)
        at org.eclipse.wst.jsdt.internal.ui.text.java.ContentAssistProcessor.collectProposals(ContentAssistProcessor.java:244)
        at org.eclipse.wst.jsdt.internal.ui.text.java.ContentAssistProcessor.computeCompletionProposals(ContentAssistProcessor.java:213)
        at org.eclipse.jface.text.contentassist.ContentAssistant.computeCompletionProposals(ContentAssistant.java:1861)
        at org.eclipse.jface.text.contentassist.CompletionProposalPopup.computeProposals(CompletionProposalPopup.java:573)
        at org.eclipse.jface.text.contentassist.CompletionProposalPopup.access$16(CompletionProposalPopup.java:570)
        at org.eclipse.jface.text.contentassist.CompletionProposalPopup$2.run(CompletionProposalPopup.java:505)
```

**Comment by angelozerr** [comment]
@lilu1990 have you again the problem with new plugin of YUI/AUI?

**Comment by lilu1990** [comment]
![aui only](https://cloud.githubusercontent.com/assets/4350803/5896494/68ae1374-a571-11e4-9d15-4a95143daff4.PNG)
![aui2 0 yui3 0](https://cloud.githubusercontent.com/assets/4350803/5896499/6ea4ef50-a571-11e4-8197-fc6d5af05f95.PNG)
![aui 1 5x yui3 0](https://cloud.githubusercontent.com/assets/4350803/5896503/743a1648-a571-11e4-964d-a2d34f374ded.PNG)


@angelozerr  I still have some problem with the code assist when there is no yui module for project , or the situation when it is a combine of aui 1.5x +yui3 , it only shows yui3 content

**Comment by angelozerr** [comment]
@lilu1990 it's a new problem, could you create an issue with this problem at https://github.com/angelozerr/tern-aui2.0.x/issues thanks!
