### ISSUE TITLE
An internal error occurred during: "Converting 'MyProject' to tern project...".

### ISSUE THREAD

**Issue by scharf** [angelozerr/tern.java#229]
I am using 0.8.0-SNAPSHOT

```
java.lang.NoSuchMethodError: tern.resources.TernProject.set(Ljava/lang/String;Lcom/eclipsesource/json/JsonValue;)Lcom/eclipsesource/json/JsonObject;
	at tern.eclipse.ide.internal.core.resources.IDETernProject.saveIDEInfos(IDETernProject.java:362)
	at tern.eclipse.ide.internal.core.resources.IDETernProject.doSave(IDETernProject.java:305)
	at tern.resources.TernProject.save(TernProject.java:302)
	at tern.resources.TernProject.createEmptyTernProjectFile(TernProject.java:362)
	at tern.resources.TernProject.doLoad(TernProject.java:351)
	at tern.eclipse.ide.internal.core.resources.IDETernProject.doLoad(IDETernProject.java:183)
	at tern.resources.TernProject.load(TernProject.java:334)
	at tern.eclipse.ide.internal.core.resources.IDEResourcesManager.getTernProject(IDEResourcesManager.java:63)
	at tern.internal.resources.InternalTernResourcesManager.getTernProject(InternalTernResourcesManager.java:46)
	at tern.TernResourcesManager.getTernProject(TernResourcesManager.java:54)
	at tern.eclipse.ide.core.TernCorePlugin.getTernProject(TernCorePlugin.java:125)
	at tern.eclipse.ide.ui.handlers.AbstractConvertProjectCommandHandler.doInstall(AbstractConvertProjectCommandHandler.java:61)
	at tern.eclipse.ide.ui.handlers.AbstractConvertProjectCommandHandler.access$0(AbstractConvertProjectCommandHandler.java:57)
	at tern.eclipse.ide.ui.handlers.AbstractConvertProjectCommandHandler$1.runInWorkspace(AbstractConvertProjectCommandHandler.java:105)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:38)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

**Comment by angelozerr** [comment]
tern.java is based on minimal-json_0.9.1.jar. See http://oss.opensagres.fr/tern.repository/0.8.0-SNAPSHOT/plugins/

Could you check please that you have several version of minimal-json in your plugins Eclipse folder.  Thanks.

**Comment by angelozerr** [comment]
@scharf now tern.java use Require-Bundle for minimal-json, could you please retry to install it to check if it resolves your problem. Thanks!

**Comment by piotrtomiak** [comment]
@angelozerr Require-Bundle in a way you did it, will still be prone to errors, passing just a version leaves it open for newer versions, which can lead to troubles, if package provider does not stick to rules and e.g. version 0.9.3 is missing a class or method. If you really want to stick to a particular version of a package, you can do it as follows:

`Import-Package: com.eclipsesource.json;version="[0.9.2,0.9.3)"`

And import package in such cases is obviously preferred way to get classes.

**Comment by scharf** [comment]
Updating the installation solved the problem. Thank you! Form my perspective the problem is solved and the issue can be closed.

**Comment by angelozerr** [comment]
> Import-Package: com.eclipsesource.json;version="[0.9.2,0.9.3)"

Thanks @piotrtomiak for your suggestion. I have done that.

@scharf could you retry to install tern.java to check if it's OK for you. Thanks

**Comment by scharf** [comment]
I cannot really tell -- I tried to restore the situation before I did my last update, but then I did not get the error anymore. Yes, the update works but I am not sure if it fixes the problem, because I cannot get it to not work. Is there something in the workspace that can make it work even with the version that had problems two days ago?

**Comment by angelozerr** [comment]
Ok, I think it's OK because import package is used (liek before) but with max/min version.

It should work. I close this issue. Thanks @scharf for your test.
