### ISSUE TITLE
error dialog popup when clicking on new JS/ESLint panels in tern module pref page

### ISSUE THREAD

**Issue by gamerson** [angelozerr/tern.java#261]
I updated my dev environment to the latest tern.java and then created a maven war project and right clicked the project to display the tern modules.  Anytime I clicked on JSLine or ESLint it would see a error dialog popup 

![workspace 1_106](https://cloud.githubusercontent.com/assets/595221/6660753/1c7dfec0-cbdb-11e4-90ba-e5f61a028c39.png)

with the following exception:

```
!ENTRY org.eclipse.jface 4 2 2015-03-16 12:43:00.803
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jface".
!STACK 0
java.lang.NullPointerException
	at java.lang.StringBuilder.<init>(StringBuilder.java:109)
	at tern.eclipse.ide.internal.ui.controls.TernModuleOptionsPanel.createUI(TernModuleOptionsPanel.java:83)
	at tern.eclipse.ide.internal.ui.controls.TernModuleOptionsPanel.createUI(TernModuleOptionsPanel.java:67)
	at tern.eclipse.ide.internal.ui.controls.AbstractTernModulePanel.<init>(AbstractTernModulePanel.java:28)
	at tern.eclipse.ide.internal.ui.controls.TernModuleOptionsPanel.<init>(TernModuleOptionsPanel.java:45)
	at tern.eclipse.ide.internal.ui.descriptors.TernModuleDescriptorManager.createOptionsPanel(TernModuleDescriptorManager.java:110)
	at tern.eclipse.ide.internal.ui.controls.OptionsPanel.createContent(OptionsPanel.java:37)
	at tern.eclipse.ide.internal.ui.controls.AbstractPanel.refresh(AbstractPanel.java:58)
	at tern.eclipse.ide.ui.controls.TernModulesBlock.refreshModule(TernModulesBlock.java:315)
	at tern.eclipse.ide.ui.controls.TernModulesBlock.access$7(TernModulesBlock.java:306)
	at tern.eclipse.ide.ui.controls.TernModulesBlock$4.selectionChanged(TernModulesBlock.java:267)
	at org.eclipse.jface.viewers.Viewer$2.run(Viewer.java:163)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil$1.run(JFaceUtil.java:50)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:178)
	at org.eclipse.jface.viewers.Viewer.fireSelectionChanged(Viewer.java:160)
	at org.eclipse.jface.viewers.StructuredViewer.updateSelection(StructuredViewer.java:2171)
	at org.eclipse.jface.viewers.StructuredViewer.handleSelect(StructuredViewer.java:1202)
	at org.eclipse.jface.viewers.CheckboxTableViewer.handleSelect(CheckboxTableViewer.java:308)
```

**Comment by gamerson** [comment]
Test project http://ge.tt/84qD9LC2/v/0?c

**Comment by angelozerr** [comment]
@gamerson I have fixed this problem, but if you wish to configure JSHint, you must import too linters projects https://github.com/angelozerr/tern.java/tree/master/eclipse/linters

I will give you a new entry Tern -> Validation -> JSHint to configure JSHint like explained here https://github.com/angelozerr/tern.java/wiki/Tern-Linter-JSHint#jshint-preferences-

**Comment by gamerson** [comment]
Confirmed its working with latest commit.

On Mon, Mar 16, 2015 at 6:58 PM, Angelo <notifications@github.com> wrote:

> @gamerson <https://github.com/gamerson> I have fixed this problem, but if
> you wish to configure JSHint, you must import too linters projects
> https://github.com/angelozerr/tern.java/tree/master/eclipse/linters
>
> I will give you a new entry Tern -> Validation -> JSHint to configure
> JSHint like explained here
> https://github.com/angelozerr/tern.java/wiki/Tern-Linter-JSHint#jshint-preferences-
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angelozerr/tern.java/issues/261#issuecomment-81580416>
> .
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com
