### ISSUE TITLE
Error in tern console

### ISSUE THREAD

**Issue by jabby** [angelozerr/tern.java#347]
I don't know what happen, but sometimes I have the following errors in tern console. I can't share the project. I will try this evening to create a case with an open source project.

-----------------------------------
Tern request#angular_type: 
{"query":{"type":"angular","subtype":"type","angularTypes":["controller"],"expression":"DateController","scope":{"module":"demoApp"},"files":["src/vendor/angular-formly/dist/formly.js","src/vendor/angular-loading-bar/build/loading-bar.js","src/vendor/angular-jwt/dist/angular-jwt.js","src/app/SocleModule.js","src/app/shared/directives/demoSimpleListWithRemove/demoSimpleListWithRemoveDirective.js","src/app/shared/directives/demoMouseTooltipGrid/demoMouseTooltipGridDirective.js","src/app/components/servicesUtil/ServicesUtilModule.js","src/app/shared/directives/demoInputPattern/demoInputPatternDirective.js","src/app/shared/demo/FormInputController.js","src/app/shared/directives/demoInputInteger/demoInputIntegerDirective.js","src/app/shared/directives/demoOutsideClick/demoOutsideClickDirective.js","src/vendor/jquery/dist/jquery.js","src/app/components/authentification/CurrentUserService.js","src/app/shared/constants/SocleConstants.js","src/app/components/authentification/AuthService.js","src/app/shared/constants/TimeoutConstants.js","src/vendor/moment/moment.js","src/vendor/angular/angular.js","src/app/shared/directives/demoLookup/demoLookupDirective.js","src/app/components/errorHandler/ErrorService.js","src/vendor/bootstrap-sass-official/assets/javascripts/bootstrap.js","src/app/components/bouchonnage/BouchonnageModule.js","src/app/shared/directives/demoCheckbox/demoCheckboxDirective.js","src/vendor/angular-mocks/angular-mocks.js","src/app/shared/directives/demoInputClear/demoInputClearDirective.js","src/app/shared/demo/ToastrController.js","src/index.html","src/app/components/bouchonnage/BouchonnageConfigService.js","src/vendor/angular-sanitize/angular-sanitize.js","src/app/shared/demo/DemoAppModule.js","test-e2e/exempleE2eTest.js","src/app/components/authentification/AuthInterceptorService.js","src/app/shared/directives/demoInputArticleNg/demoInputArticleNgDirective.js","src/vendor/angular-toastr/dist/angular-toastr.tpls.js","src/app/shared/demo/LookupMultiselectDirectiveController.js","src/vendor/restangular/dist/restangular.js","src/app/components/formulaire/FormulaireModule.js","src/app/components/popIn/PopInModule.js","conf/protractor/protractor.config.js","src/app/components/popIn/PopInAlertController.js","src/vendor/angular-ui-bootstrap-bower/ui-bootstrap-tpls.js","src/app/shared/demo/ErreursController.js","src/app/shared/demo/GridDirectiveController.js","src/vendor/angular-cookies/angular-cookies.js","src/vendor/api-check/dist/api-check.js","src/app/components/formulaire/FormulaireService.js","src/app/shared/directives/demoToggleCheckbox/demoToggleCheckboxDirective.js","Gruntfile.js","src/app/components/bouchonnage/BouchonnageInterceptorService.js","src/app/components/servicesUtil/LocalStorageService.js","src/vendor/angular-ui-router/release/angular-ui-router.js","conf/karma/karma.config.js","src/app/shared/constants/TypeExceptionConstants.js","src/vendor/ngDialog/js/ngDialog.js","src/app/shared/directives/demoSpinner/demoSpinnerDirective.js","src/app/shared/directives/demoRadioInput/demoRadioInputDirective.js","src/app/shared/demo/DateController.js","src/app/components/errorHandler/ErrorHandlerModule.js","src/vendor/angular-logger/dist/angular-logger.min.js","src/app/shared/directives/demoDirectiveModule.js","src/vendor/oclazyload/dist/ocLazyLoad.js","src/vendor/sprintf/src/sprintf.js","src/assets/libs/angular-locale/angular-locale_fr-fr.js","src/vendor/lodash/lodash.js","src/vendor/angular-ui-grid/ui-grid.js","src/app/shared/directives/demoGrid/demoGridDirective.js","src/vendor/a0-angular-storage/dist/angular-storage.js","src/app/components/authentification/AuthentificationModule.js","src/app/shared/directives/demoKeyEnterPressed/demoKeyEnterPressedDirective.js","src/app/shared/directives/demoPopIn/demoPopInDirective.js","src/app/components/popIn/PopInAlertService.js","src/app/shared/demo/LookupDirectiveController.js","src/app/shared/directives/demoTagManager/demoTagManagerDirective.js","src/vendor/angular-logger/dist/angular-logger.js","src/app/shared/directives/demoInputNumber/demoInputNumberDirective.js","src/app/shared/demo/ButtonController.js","src/app/shared/directives/demoMouseTooltip/demoMouseTooltipDirective.js","src/app/shared/directives/demoComboboxCheckbox/demoComboboxCheckboxDirective.js","src/app/components/errorHandler/HttpErrorsInterceptorService.js","src/vendor/ng-scrollbar/dist/ng-scrollbar.js","src/vendor/angular-resource/angular-resource.js","conf/protractor/protractor-ci.config.js","src/app/components/servicesUtil/EnvConstants.js","src/vendor/angular-messages/angular-messages.js","src/app/exempleUnitTest.js","src/vendor/angular-breadcrumb/release/angular-breadcrumb.js","src/app/shared/demo/DropDController.js","src/vendor/tracekit/tracekit.js"],"file":"src/index.html"}}
-----------------------------------
tern.TernException: TypeError: Cannot read property 'name' of undefined
	at tern.server.nodejs.NodejsTernHelper.makeRequest(NodejsTernHelper.java:86)
	at tern.server.nodejs.NodejsTernServer.makeRequest(NodejsTernServer.java:163)
	at tern.server.nodejs.NodejsTernServer.request(NodejsTernServer.java:127)
	at tern.server.protocol.TernResultsProcessorsFactory.makeRequestAndProcess(TernResultsProcessorsFactory.java:40)
	at tern.eclipse.ide.internal.core.resources.IDETernServerAsyncReqProcessor.processRequest(IDETernServerAsyncReqProcessor.java:49)
	at tern.server.AbstractTernServer.request(AbstractTernServer.java:167)
	at tern.resources.TernProject.request(TernProject.java:631)
	at org.eclipse.angularjs.core.validation.ValidatorUtils.isAngularElementExists(ValidatorUtils.java:247)
	at org.eclipse.angularjs.core.validation.ValidatorUtils.validate(ValidatorUtils.java:190)
	at org.eclipse.angularjs.core.validation.ValidatorUtils.validate(ValidatorUtils.java:158)
	at org.eclipse.angularjs.core.validation.ValidatorUtils.validateFile(ValidatorUtils.java:150)
	at org.eclipse.angularjs.core.validation.HTMLAngularValidator.validate(HTMLAngularValidator.java:44)
	at org.eclipse.wst.validation.Validator$V2.validate(Validator.java:1159)
	at org.eclipse.wst.validation.internal.ValManager.validate(ValManager.java:704)
	at org.eclipse.wst.validation.internal.ValManager$1.visit(ValManager.java:665)
	at org.eclipse.wst.validation.internal.ValManager.accept(ValManager.java:783)
	at org.eclipse.wst.validation.internal.ValManager.validate(ValManager.java:669)
	at org.eclipse.wst.validation.internal.ValidationRunner.execute(ValidationRunner.java:134)
	at org.eclipse.wst.validation.internal.ValidationRunner.run(ValidationRunner.java:148)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.wst.validation.internal.ValidationRunner.validate(ValidationRunner.java:67)
	at org.eclipse.wst.validation.ValidationFramework.validate(ValidationFramework.java:661)
	at tern.eclipse.ide.linter.internal.ui.validation.RefreshTernValidator$ValidateJob.run(RefreshTernValidator.java:86)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

Tern error#angular_type with 14ms: 

{"query":{"type":"angular","subtype":"type","angularTypes":["controller"],"expression":"FormInputController","scope":{"module":"demoApp"},"files":["src/vendor/angular-formly/dist/formly.js","src/vendor/angular-loading-bar/build/loading-bar.js","src/vendor/angular-jwt/dist/angular-jwt.js","src/app/SocleModule.js","src/app/shared/directives/demoSimpleListWithRemove/demoSimpleListWithRemoveDirective.js","src/app/shared/directives/demoMouseTooltipGrid/demoMouseTooltipGridDirective.js","src/app/components/servicesUtil/ServicesUtilModule.js","src/app/shared/directives/demoInputPattern/demoInputPatternDirective.js","src/app/shared/demo/FormInputController.js","src/app/shared/directives/demoInputInteger/demoInputIntegerDirective.js","src/app/shared/directives/demoOutsideClick/demoOutsideClickDirective.js","src/vendor/jquery/dist/jquery.js","src/app/components/authentification/CurrentUserService.js","src/app/shared/constants/SocleConstants.js","src/app/components/authentification/AuthService.js","src/app/shared/constants/TimeoutConstants.js","src/vendor/moment/moment.js","src/vendor/angular/angular.js","src/app/shared/directives/demoLookup/demoLookupDirective.js","src/app/components/errorHandler/ErrorService.js","src/vendor/bootstrap-sass-official/assets/javascripts/bootstrap.js","src/app/components/bouchonnage/BouchonnageModule.js","src/app/shared/directives/demoCheckbox/demoCheckboxDirective.js","src/vendor/angular-mocks/angular-mocks.js","src/app/shared/directives/demoInputClear/demoInputClearDirective.js","src/app/shared/demo/ToastrController.js","src/index.html","src/app/components/bouchonnage/BouchonnageConfigService.js","src/vendor/angular-sanitize/angular-sanitize.js","src/app/shared/demo/DemoAppModule.js","test-e2e/exempleE2eTest.js","src/app/components/authentification/AuthInterceptorService.js","src/app/shared/directives/demoInputArticleNg/demoInputArticleNgDirective.js","src/vendor/angular-toastr/dist/angular-toastr.tpls.js","src/app/shared/demo/LookupMultiselectDirectiveController.js","src/vendor/restangular/dist/restangular.js","src/app/components/formulaire/FormulaireModule.js","src/app/components/popIn/PopInModule.js","conf/protractor/protractor.config.js","src/app/components/popIn/PopInAlertController.js","src/vendor/angular-ui-bootstrap-bower/ui-bootstrap-tpls.js","src/app/shared/demo/ErreursController.js","src/app/shared/demo/GridDirectiveController.js","src/vendor/angular-cookies/angular-cookies.js","src/vendor/api-check/dist/api-check.js","src/app/components/formulaire/FormulaireService.js","src/app/shared/directives/demoToggleCheckbox/demoToggleCheckboxDirective.js","Gruntfile.js","src/app/components/bouchonnage/BouchonnageInterceptorService.js","src/app/components/servicesUtil/LocalStorageService.js","src/vendor/angular-ui-router/release/angular-ui-router.js","conf/karma/karma.config.js","src/app/shared/constants/TypeExceptionConstants.js","src/vendor/ngDialog/js/ngDialog.js","src/app/shared/directives/demoSpinner/demoSpinnerDirective.js","src/app/shared/directives/demoRadioInput/demoRadioInputDirective.js","src/app/shared/demo/DateController.js","src/app/components/errorHandler/ErrorHandlerModule.js","src/vendor/angular-logger/dist/angular-logger.min.js","src/app/shared/directives/demoDirectiveModule.js","src/vendor/oclazyload/dist/ocLazyLoad.js","src/vendor/sprintf/src/sprintf.js","src/assets/libs/angular-locale/angular-locale_fr-fr.js","src/vendor/lodash/lodash.js","src/vendor/angular-ui-grid/ui-grid.js","src/app/shared/directives/demoGrid/demoGridDirective.js","src/vendor/a0-angular-storage/dist/angular-storage.js","src/app/components/authentification/AuthentificationModule.js","src/app/shared/directives/demoKeyEnterPressed/demoKeyEnterPressedDirective.js","src/app/shared/directives/demoPopIn/demoPopInDirective.js","src/app/components/popIn/PopInAlertService.js","src/app/shared/demo/LookupDirectiveController.js","src/app/shared/directives/demoTagManager/demoTagManagerDirective.js","src/vendor/angular-logger/dist/angular-logger.js","src/app/shared/directives/demoInputNumber/demoInputNumberDirective.js","src/app/shared/demo/ButtonController.js","src/app/shared/directives/demoMouseTooltip/demoMouseTooltipDirective.js","src/app/shared/directives/demoComboboxCheckbox/demoComboboxCheckboxDirective.js","src/app/components/errorHandler/HttpErrorsInterceptorService.js","src/vendor/ng-scrollbar/dist/ng-scrollbar.js","src/vendor/angular-resource/angular-resource.js","conf/protractor/protractor-ci.config.js","src/app/components/servicesUtil/EnvConstants.js","src/vendor/angular-messages/angular-messages.js","src/app/exempleUnitTest.js","src/vendor/angular-breadcrumb/release/angular-breadcrumb.js","src/app/shared/demo/DropDController.js","src/vendor/tracekit/tracekit.js"],"file":"src/index.html"}}
Tern request#angular_type: 
-----------------------------------
-----------------------------------
tern.TernException: TypeError: Cannot read property 'name' of undefined
	at tern.server.nodejs.NodejsTernHelper.makeRequest(NodejsTernHelper.java:86)
	at tern.server.nodejs.NodejsTernServer.makeRequest(NodejsTernServer.java:163)
	at tern.server.nodejs.NodejsTernServer.request(NodejsTernServer.java:127)
	at tern.server.protocol.TernResultsProcessorsFactory.makeRequestAndProcess(TernResultsProcessorsFactory.java:40)
	at tern.eclipse.ide.internal.core.resources.IDETernServerAsyncReqProcessor.processRequest(IDETernServerAsyncReqProcessor.java:49)
	at tern.server.AbstractTernServer.request(AbstractTernServer.java:167)
	at tern.resources.TernProject.request(TernProject.java:631)
	at org.eclipse.angularjs.core.validation.ValidatorUtils.isAngularElementExists(ValidatorUtils.java:247)
	at org.eclipse.angularjs.core.validation.ValidatorUtils.validate(ValidatorUtils.java:190)
	at org.eclipse.angularjs.core.validation.ValidatorUtils.validate(ValidatorUtils.java:158)
	at org.eclipse.angularjs.core.validation.ValidatorUtils.validateFile(ValidatorUtils.java:150)
	at org.eclipse.angularjs.core.validation.HTMLAngularValidator.validate(HTMLAngularValidator.java:44)
	at org.eclipse.wst.validation.Validator$V2.validate(Validator.java:1159)
	at org.eclipse.wst.validation.internal.ValManager.validate(ValManager.java:704)
	at org.eclipse.wst.validation.internal.ValManager$1.visit(ValManager.java:665)
	at org.eclipse.wst.validation.internal.ValManager.accept(ValManager.java:783)
	at org.eclipse.wst.validation.internal.ValManager.validate(ValManager.java:669)
	at org.eclipse.wst.validation.internal.ValidationRunner.execute(ValidationRunner.java:134)
	at org.eclipse.wst.validation.internal.ValidationRunner.run(ValidationRunner.java:148)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.wst.validation.internal.ValidationRunner.validate(ValidationRunner.java:67)
	at org.eclipse.wst.validation.ValidationFramework.validate(ValidationFramework.java:661)
	at tern.eclipse.ide.linter.internal.ui.validation.RefreshTernValidator$ValidateJob.run(RefreshTernValidator.java:86)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

Tern error#angular_type with 22ms: 

{"query":{"type":"angular","subtype":"type","angularTypes":["controller"],"expression":"DropDController","scope":{"module":"demoApp"},"files":["src/vendor/angular-formly/dist/formly.js","src/vendor/angular-loading-bar/build/loading-bar.js","src/vendor/angular-jwt/dist/angular-jwt.js","src/app/SocleModule.js","src/app/shared/directives/demoSimpleListWithRemove/demoSimpleListWithRemoveDirective.js","src/app/shared/directives/demoMouseTooltipGrid/demoMouseTooltipGridDirective.js","src/app/components/servicesUtil/ServicesUtilModule.js","src/app/shared/directives/demoInputPattern/demoInputPatternDirective.js","src/app/shared/demo/FormInputController.js","src/app/shared/directives/demoInputInteger/demoInputIntegerDirective.js","src/app/shared/directives/demoOutsideClick/demoOutsideClickDirective.js","src/vendor/jquery/dist/jquery.js","src/app/components/authentification/CurrentUserService.js","src/app/shared/constants/SocleConstants.js","src/app/components/authentification/AuthService.js","src/app/shared/constants/TimeoutConstants.js","src/vendor/moment/moment.js","src/vendor/angular/angular.js","src/app/shared/directives/demoLookup/demoLookupDirective.js","src/app/components/errorHandler/ErrorService.js","src/vendor/bootstrap-sass-official/assets/javascripts/bootstrap.js","src/app/components/bouchonnage/BouchonnageModule.js","src/app/shared/directives/demoCheckbox/demoCheckboxDirective.js","src/vendor/angular-mocks/angular-mocks.js","src/app/shared/directives/demoInputClear/demoInputClearDirective.js","src/app/shared/demo/ToastrController.js","src/index.html","src/app/components/bouchonnage/BouchonnageConfigService.js","src/vendor/angular-sanitize/angular-sanitize.js","src/app/shared/demo/DemoAppModule.js","test-e2e/exempleE2eTest.js","src/app/components/authentification/AuthInterceptorService.js","src/app/shared/directives/demoInputArticleNg/demoInputArticleNgDirective.js","src/vendor/angular-toastr/dist/angular-toastr.tpls.js","src/app/shared/demo/LookupMultiselectDirectiveController.js","src/vendor/restangular/dist/restangular.js","src/app/components/formulaire/FormulaireModule.js","src/app/components/popIn/PopInModule.js","conf/protractor/protractor.config.js","src/app/components/popIn/PopInAlertController.js","src/vendor/angular-ui-bootstrap-bower/ui-bootstrap-tpls.js","src/app/shared/demo/ErreursController.js","src/app/shared/demo/GridDirectiveController.js","src/vendor/angular-cookies/angular-cookies.js","src/vendor/api-check/dist/api-check.js","src/app/components/formulaire/FormulaireService.js","src/app/shared/directives/demoToggleCheckbox/demoToggleCheckboxDirective.js","Gruntfile.js","src/app/components/bouchonnage/BouchonnageInterceptorService.js","src/app/components/servicesUtil/LocalStorageService.js","src/vendor/angular-ui-router/release/angular-ui-router.js","conf/karma/karma.config.js","src/app/shared/constants/TypeExceptionConstants.js","src/vendor/ngDialog/js/ngDialog.js","src/app/shared/directives/demoSpinner/demoSpinnerDirective.js","src/app/shared/directives/demoRadioInput/demoRadioInputDirective.js","src/app/shared/demo/DateController.js","src/app/components/errorHandler/ErrorHandlerModule.js","src/vendor/angular-logger/dist/angular-logger.min.js","src/app/shared/directives/demoDirectiveModule.js","src/vendor/oclazyload/dist/ocLazyLoad.js","src/vendor/sprintf/src/sprintf.js","src/assets/libs/angular-locale/angular-locale_fr-fr.js","src/vendor/lodash/lodash.js","src/vendor/angular-ui-grid/ui-grid.js","src/app/shared/directives/demoGrid/demoGridDirective.js","src/vendor/a0-angular-storage/dist/angular-storage.js","src/app/components/authentification/AuthentificationModule.js","src/app/shared/directives/demoKeyEnterPressed/demoKeyEnterPressedDirective.js","src/app/shared/directives/demoPopIn/demoPopInDirective.js","src/app/components/popIn/PopInAlertService.js","src/app/shared/demo/LookupDirectiveController.js","src/app/shared/directives/demoTagManager/demoTagManagerDirective.js","src/vendor/angular-logger/dist/angular-logger.js","src/app/shared/directives/demoInputNumber/demoInputNumberDirective.js","src/app/shared/demo/ButtonController.js","src/app/shared/directives/demoMouseTooltip/demoMouseTooltipDirective.js","src/app/shared/directives/demoComboboxCheckbox/demoComboboxCheckboxDirective.js","src/app/components/errorHandler/HttpErrorsInterceptorService.js","src/vendor/ng-scrollbar/dist/ng-scrollbar.js","src/vendor/angular-resource/angular-resource.js","conf/protractor/protractor-ci.config.js","src/app/components/servicesUtil/EnvConstants.js","src/vendor/angular-messages/angular-messages.js","src/app/exempleUnitTest.js","src/vendor/angular-breadcrumb/release/angular-breadcrumb.js","src/app/shared/demo/DropDController.js","src/vendor/tracekit/tracekit.js"],"file":"src/index.html"}}
Tern request#angular_type: 
-----------------------------------
-----------------------------------
tern.TernException: TypeError: Cannot read property 'name' of undefined
	at tern.server.nodejs.NodejsTernHelper.makeRequest(NodejsTernHelper.java:86)
	at tern.server.nodejs.NodejsTernServer.makeRequest(NodejsTernServer.java:163)
	at tern.server.nodejs.NodejsTernServer.request(NodejsTernServer.java:127)
	at tern.server.protocol.TernResultsProcessorsFactory.makeRequestAndProcess(TernResultsProcessorsFactory.java:40)
	at tern.eclipse.ide.internal.core.resources.IDETernServerAsyncReqProcessor.processRequest(IDETernServerAsyncReqProcessor.java:49)
	at tern.server.AbstractTernServer.request(AbstractTernServer.java:167)
	at tern.resources.TernProject.request(TernProject.java:631)
	at org.eclipse.angularjs.core.validation.ValidatorUtils.isAngularElementExists(ValidatorUtils.java:247)
	at org.eclipse.angularjs.core.validation.ValidatorUtils.validate(ValidatorUtils.java:190)
	at org.eclipse.angularjs.core.validation.ValidatorUtils.validate(ValidatorUtils.java:158)
	at org.eclipse.angularjs.core.validation.ValidatorUtils.validateFile(ValidatorUtils.java:150)
	at org.eclipse.angularjs.core.validation.HTMLAngularValidator.validate(HTMLAngularValidator.java:44)
	at org.eclipse.wst.validation.Validator$V2.validate(Validator.java:1159)
	at org.eclipse.wst.validation.internal.ValManager.validate(ValManager.java:704)
	at org.eclipse.wst.validation.internal.ValManager$1.visit(ValManager.java:665)
	at org.eclipse.wst.validation.internal.ValManager.accept(ValManager.java:783)
	at org.eclipse.wst.validation.internal.ValManager.validate(ValManager.java:669)
	at org.eclipse.wst.validation.internal.ValidationRunner.execute(ValidationRunner.java:134)
	at org.eclipse.wst.validation.internal.ValidationRunner.run(ValidationRunner.java:148)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2241)
	at org.eclipse.wst.validation.internal.ValidationRunner.validate(ValidationRunner.java:67)
	at org.eclipse.wst.validation.ValidationFramework.validate(ValidationFramework.java:661)
	at tern.eclipse.ide.linter.internal.ui.validation.RefreshTernValidator$ValidateJob.run(RefreshTernValidator.java:86)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

Tern error#angular_type with 12ms: 

Tern response# with 120ms: 
{}
-----------------------------------

**Comment by angelozerr** [comment]
Yes please give me a very simple sample. Thanks!

**Comment by angelozerr** [comment]
@jabby could you tery with 1.2.0-SNAPSHOT. I have done a lot of improvement. Hope it will fix this issue, otherwise please share your project. Thanks.

**Comment by jabby** [comment]
I will take a look this week.
