### ISSUE TITLE
 TernException during code completion

### ISSUE THREAD

**Issue by vrubezhny** [angelozerr/tern.java#415]
An exception has occured when using content assist on html5 file

tern.TernException: 127.0.0.1:50063 failed to respond
	at tern.server.DefaultResponseHandler.getData(DefaultResponseHandler.java:45)
	at tern.server.protocol.TernResultsProcessorsFactory.makeRequestAndProcess(TernResultsProcessorsFactory.java:43)
	at tern.eclipse.ide.internal.core.resources.IDETernServerAsyncReqProcessor.run(IDETernServerAsyncReqProcessor.java:104)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
Caused by: org.apache.http.NoHttpResponseException: 127.0.0.1:50063 failed to respond
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
	at org.apache.http.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:283)
	at org.apache.http.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:251)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.receiveResponseHeader(ManagedClientConnectionImpl.java:197)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
	at org.apache.http.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:685)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:487)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:863)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at tern.server.nodejs.NodejsTernHelper.makeRequest(NodejsTernHelper.java:74)
	at tern.server.nodejs.NodejsTernServer.makeRequest(NodejsTernServer.java:163)
	at tern.server.nodejs.NodejsTernServer.request(NodejsTernServer.java:127)
	at tern.server.protocol.TernResultsProcessorsFactory.makeRequestAndProcess(TernResultsProcessorsFactory.java:42)
	... 2 more

How to reproduce:
1. import this project http://mvnrepository.com/artifact/org.jboss.aerogear.archetypes/jboss-html5-mobile-archetype/7.1.3.Final

2. open src/main/webapp/index.html
3. try calling content assist and check error log

**Comment by angelozerr** [comment]
@vrubezhny which version of tern.java do you use? I cannot reproduce it with 1.2.0-SNAPSHOT?

**Comment by vrubezhny** [comment]
At the moment for jbosstools-4.3.x we force the dependencies to Tern.java from 1.1.0 and higher. 
So, it actually can be any of Tern version starting from 1.1.0.

**Comment by angelozerr** [comment]
@vrubezhny could you check please that with tern 1.2.0 it works. I would like to avoid doing some patches for old version of tern.java. I'm sorry I have no time to do that -(

**Comment by vrubezhny** [comment]
No need to patch the older versions. We're ok if that issue is fixed in latest version.
But I don't know if it's really fixed. The code in stack trace just catches the exception and logs it, and there is not a clue on why that "failed to respond" error has occurred.

**Comment by angelozerr** [comment]
It's difficult to discover the problem with just with stacktrace.

Here my test context:

 * tern 1.2.0-SNAPSHOT 
 * `.tern-project`:

```json
{
  "ecmaVersion": 5,
  "plugins": {
    "guess-types": {
      
    },
    "outline": {
      
    }
  }
}
```

 * I open completion inside `src/main/webapp/index.html` and I have:

![areogar](https://cloud.githubusercontent.com/assets/1932211/14824025/c48ad068-0bd4-11e6-916c-6905f1d7f787.png)
