### ISSUE TITLE
NullPointerException when attempting to convert project to tern

### ISSUE THREAD

**Issue by mgeorgy** [angelozerr/tern.java#433]
I'm new to Tern and have followed the installation instructions.  After creating a general project, I attempt to convert the project to a tern project from the Project Explorer and receive the follwing error:

!ENTRY org.eclipse.core.jobs 4 2 2016-07-26 02:38:44.354
!MESSAGE An internal error occurred during: "Converting '<project_name>' to tern project...".
!STACK 0
java.lang.NullPointerException
        at tern.eclipse.ide.internal.core.resources.IDETernProject.<init>(IDETernProject.java:118)
        at tern.eclipse.ide.internal.core.resources.IDEResourcesManager.getTernProject(IDEResourcesManager.java:61)
        at tern.internal.resources.InternalTernResourcesManager.getTernProject(InternalTernResourcesManager.java:47)
        at tern.TernResourcesManager.getTernProject(TernResourcesManager.java:58)
        at tern.eclipse.ide.core.TernCorePlugin.getTernProject(TernCorePlugin.java:131)
        at tern.eclipse.ide.ui.handlers.AbstractConvertProjectCommandHandler.doInstall(AbstractConvertProjectCommandHandler.java:70)
        at tern.eclipse.ide.ui.handlers.AbstractConvertProjectCommandHandler.access$0(AbstractConvertProjectCommandHandler.java:66)
        at tern.eclipse.ide.ui.handlers.AbstractConvertProjectCommandHandler$1.runInWorkspace(AbstractConvertProjectCommandHandler.java:113)
        at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

I am using Eclipse 4.6 on OS X 10.11.6.

Any ideas what maybe causing this?

Thanks

**Comment by angelozerr** [comment]
It seems the location of your project is null? https://github.com/angelozerr/tern.java/blob/master/eclipse/tern.eclipse.ide.core/src/tern/eclipse/ide/internal/core/resources/IDETernProject.java#L118

Have you created your project in the default location of the workspace?

**Comment by mgeorgy** [comment]
Thank you.  It is working without a problem if my project is created in my workspace.  Is there an issue if I wanted to create the project on a remote server using RSE?

**Comment by angelozerr** [comment]
I have never used RSE. tern.java uses project location, because tern.js need a working directory (file system). I'm not sure if it can work with RSE?
