### ISSUE TITLE
Tern throws exception when deleting project which is closed

### ISSUE THREAD

**Issue by rawagner** [angelozerr/tern.java#440]
Steps to reproduce:
1. use new & clean workspace
2. create some project (java project is enough)
3. close it
4. delete
5. check error log

`org.eclipse.core.internal.resources.ResourceException: Resource '/NewCdiProject' is not open.
	at org.eclipse.core.internal.resources.Project.checkAccessible(Project.java:144)
	at org.eclipse.core.internal.resources.Resource.checkAccessibleAndLocal(Resource.java:215)
	at org.eclipse.core.internal.resources.Resource.getSessionProperty(Resource.java:1207)
	at tern.eclipse.ide.internal.core.resources.IDETernProject.getTernProject(IDETernProject.java:708)
	at tern.eclipse.ide.internal.core.resources.IDETernProjectSynchronizer.disposeTernProject(IDETernProjectSynchronizer.java:93)
	at tern.eclipse.ide.internal.core.resources.IDETernProjectSynchronizer.resourceChanged(IDETernProjectSynchronizer.java:69)
	at org.eclipse.core.internal.events.NotificationManager$1.run(NotificationManager.java:299)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.core.internal.events.NotificationManager.notify(NotificationManager.java:289)
	at org.eclipse.core.internal.events.NotificationManager.handleEvent(NotificationManager.java:265)
	at org.eclipse.core.internal.resources.Workspace.broadcastEvent(Workspace.java:369)
	at org.eclipse.core.internal.resources.Resource.broadcastPreDeleteEvent(Resource.java:1885)
	at org.eclipse.core.internal.resources.Resource.delete(Resource.java:767)
	at org.eclipse.core.internal.resources.Project.delete(Project.java:318)
	at org.eclipse.ltk.core.refactoring.resource.DeleteResourceChange.perform(DeleteResourceChange.java:155)
	at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:280)
	at org.eclipse.ltk.core.refactoring.CompositeChange.perform(CompositeChange.java:280)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation$1.run(PerformChangeOperation.java:257)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.executeChange(PerformChangeOperation.java:305)
	at org.eclipse.ltk.internal.ui.refactoring.UIPerformChangeOperation.executeChange(UIPerformChangeOperation.java:96)
	at org.eclipse.ltk.core.refactoring.PerformChangeOperation.run(PerformChangeOperation.java:216)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
	at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2267)
	at org.eclipse.ltk.internal.ui.refactoring.WorkbenchRunnableAdapter.run(WorkbenchRunnableAdapter.java:86)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:119)`

**Comment by angelozerr** [comment]
Thanks @rawagner for your explanation. Problem is now fixed.
