### ISSUE TITLE
java.lang.RuntimeException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by digable1** [angelozerr/tern.java#447]
at tern.eclipse.ide.core.resources.MyEclipseResourcesDelegatingManager.init(MyEclipseResourcesDelegatingManager.java:44)
        at tern.eclipse.ide.core.resources.MyEclipseResourcesDelegatingManager.isHTMLFile(MyEclipseResourcesDelegatingManager.java:74)
        at tern.internal.resources.InternalTernResourcesManager.isHTMLFile(InternalTernResourcesManager.java:77)
        at tern.TernResourcesManager.isHTMLFile(TernResourcesManager.java:66)
        at tern.eclipse.ide.internal.ui.EditorActivationTracker.partActivated(EditorActivationTracker.java:74)
        at org.eclipse.ui.internal.WorkbenchPage$14.run(WorkbenchPage.java:4977)

I get this every few clicks, especially as I change editors in Eclipse.  Or run a JUnit test, etc.

This started happening today when I installed your Angular2 IDE - and I previously and still have the Palantir Typescript, which apparently uses your Typescript as I look at the installation plug-ins.

Obviously this is more than annoying - makes my Eclipse installation barely usable now.  Any ideas - hopefully that doesn't involve a complete clean re-install?

**Comment by angelozerr** [comment]
@piotrtomiak I think it's a bug with MyEclipse?

**Comment by faxik** [comment]
I also have exactly the same issue and also attribute it to Angular 2 IDE. Any solution other than rollback?

**Comment by skinny-jones** [comment]
I got the same problem, any solution so far? It seems I will have to re install Eclipse

**Comment by piotrtomiak** [comment]
@digable1, @skinny-jones, @faxik - this issue may happen if you uninstall Webclipse JSjet, which is using enhanced version of Angelo's Tern.java project. JSjet is part of Genuitec Angular IDE as well. Unfortunately due problems with Eclipse P2 (which manages plugins), some plugins are left after uninstallation. This error happens, because `com.genuitec.eclipse.javascript.tern` bundle is not present in your installation, but our patched version of `tern.eclipse.ide.core` is, but it shouldn't. We have mitigated one of such issues, but looks like we will need to do more to address it. I am sorry for your problems. At this point, the only thing I can suggest is clean reinstall of Eclipse, or manual removal of problematic java.tern bundles from `{eclipse-installation}/configuration/org.eclipse.equinox.simpleconfigurator/bundles.info` - just remove all lines with `tern` in the name.

May I ask you why you've decided to uninstall Angular IDE?

**Comment by angelozerr** [comment]
Thanks @piotrtomiak for your great explanation!

If there are something to do in tern.java to fix your problem, don't hesitate to do a PR.

**Comment by piotrtomiak** [comment]
> If there are something to do in tern.java to fix your problem, don't hesitate to do a PR.
Thanks, but unfortunately that's just some P2 mess we need to figure out.
